name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: 8byte-devops-app
  EC2_INSTANCE_ID: i-054dae028a48968be
  CONTAINER_NAME: 8byte-devops-container

jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::777040315554:role/8byte-github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
            777040315554.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Push Docker image to ECR
        run: |
          docker push \
            777040315554.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:${{ github.sha }}

      - name: Deploy to EC2
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "$EC2_INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 777040315554.dkr.ecr.ap-south-1.amazonaws.com",
              "docker pull 777040315554.dkr.ecr.ap-south-1.amazonaws.com/8byte-devops-app:${{ github.sha }}",
              "docker stop 8byte-devops-container || true",
              "docker rm 8byte-devops-container || true",
              "docker run -d --restart unless-stopped --name 8byte-devops-container -p 5000:5000 777040315554.dkr.ecr.ap-south-1.amazonaws.com/8byte-devops-app:${{ github.sha }}"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID"

          aws ssm get-command-invocation \
            --command-id "$COMMAND_ID" \
            --instance-id "$EC2_INSTANCE_ID"